### ISSUE TITLE
initialize_graph_for_user_auth

### ISSUE THREAD

**Issue by rmdodhia** [microsoftgraph/microsoft-graph-training#122]
In the section "Add user authentication", there's a reference to a function initialize_graph_for_user_auth. It doesn't appear in the code, though. I suspect that's why I get errors like this:

azure.core.exceptions.ClientAuthenticationError: Couldn't begin authentication: AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.

**Comment by jasonjoh** [comment]
Sorry for the confusion! `initialize_graph_for_user_auth` is a typo, it should just be referring to the `__init__`.

The error you're seeing indicates a tenant configuration issue. I typically see this error if:

- You registered the app to only allow "Users in my organization only", but you left `authTenant` as `common`. If this is your case, change `authTenant` to your tenant ID.
- You registered the app to allow "Users from any organization and personal accounts", but set `authTenant` to your tenant ID. If this is your case, change `authTenant` to `common`.

That being said, I know this config setup is confusing. An updated tutorial is coming out today that simplifies.

**Comment by jasonjoh** [comment]
Updated tutorial is live at https://learn.microsoft.com/en-us/graph/tutorials/python.
