### ISSUE TITLE
ModuleNotFoundError: No module named 'kiota_authentication_azure'

### ISSUE THREAD

**Issue by bbrendon** [microsoftgraph/microsoft-graph-training#136]

**Comment by bbrendon** [comment]
Tried this tutorial. Fails. 
https://learn.microsoft.com/en-us/graph/tutorials/python-app-only?tabs=aad&tutorial-step=2

**Comment by jasonjoh** [comment]
Sorry to hear that @bbrendon. At what point does it fail for you? The Python SDK is in preview so it is possible something has changed. I will revalidate the steps.

**Comment by jasonjoh** [comment]
I believe this is caused by an error in the instructions. Instead of msgraph-core, you should install msgraph-sdk. I will get this fixed in the tutorial.

**Comment by jasonjoh** [comment]
Let me know if this didn't fix your issue.
