### ISSUE TITLE
Update Go tutorial samples to remove prefix

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/microsoft-graph-training#140]
Related to https://github.com/microsoftgraph/msgraph-sdk-go/issues/397

Remove the package prefix in query parameter structs in tutorial documentation for go. e.g `Me`  from package`"github.com/microsoftgraph/msgraph-sdk-go/me"`
i.e
```go
query := me.MeMailFoldersItemMessagesRequestBuilderGetQueryParameters
```
should be 
```go
query := me.MailFoldersItemMessagesRequestBuilderGetQueryParameters
```

**Comment by jasonjoh** [comment]
It appears this is a breaking change in the SDK as this was the correct struct name in 0.48.0.
