### ISSUE TITLE
Issue with Microsoft Graph Version 5.0.0.

### ISSUE THREAD

**Issue by MarvinBangert** [microsoftgraph/microsoft-graph-training#145]
Related to [dotnet app only](https://github.com/microsoftgraph/microsoft-graph-training/blob/main/tutorials/dotnet-app-only.yml) and [dotnet](https://github.com/microsoftgraph/microsoft-graph-training/blob/main/tutorials/dotnet.yml)

properly also related to: #144 

I receive an error on "IGraphServiceUsersCollectionPage" and "Request()".
![image](https://user-images.githubusercontent.com/50577590/223197689-04874401-e4fc-4c58-a482-33091baaf4f3.png)

Microsoft Graph SDK v5 removed request(): [Removal of request from the fluent api](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#removal-of-request-from-the-fluent-api)

My fix was updating the package reference for Microsoft graph from 5.0.0 to the latest v4: 4.54.0
![image](https://user-images.githubusercontent.com/50577590/223198504-26ce0ec9-6ec8-4ab8-bee8-b36b730b70d4.png)

![image](https://user-images.githubusercontent.com/50577590/223198573-7961f96f-9040-427a-8051-7eccfdf27559.png)

Otherwise maybe update the script within GraphHelper.cs? I am not quite sure how....

**Comment by jasonjoh** [comment]
See https://github.com/microsoftgraph/microsoft-graph-training/pull/144, this will be published on our site shortly.
