### ISSUE TITLE
Tutorial suggests using non-browsable constructor to create credential

### ISSUE THREAD

**Issue by carlossanlop** [microsoftgraph/microsoft-graph-training#147]
Page: https://github.com/microsoftgraph/microsoft-graph-training/blob/main/tutorials/dotnet.yml

In the section titled "Configure Graph client for user authentication" of that page, under step 2 ("Add the following code to the GraphHelper class"), the code example suggest creating the credential using:

```cs
_deviceCodeCredential = new DeviceCodeCredential(deviceCodePrompt,
        settings.TenantId, settings.ClientId);
```

But that constructor is marked with the `[EditorBrowsable(EditorBrowsableState.Never)]` attribute in source: https://github.com/Azure/azure-sdk-for-net/blob/276e381fa973105926f1847181d6f141585722b3/sdk/identity/Azure.Identity/src/Credentials/DeviceCodeCredential.cs#L56-L57

 which prevents it from showing up in intellisense:

![image](https://user-images.githubusercontent.com/1175054/224569022-f7020afe-108c-4164-abf2-18653148e186.png)

![image](https://user-images.githubusercontent.com/1175054/224569029-a9162b75-99dd-499d-b35a-bb24e39f8a2c.png)

or among the available constructors in MS Docs: https://learn.microsoft.com/en-us/dotnet/api/azure.identity.devicecodecredential.-ctor?view=azure-dotnet 

Should we be suggesting new users to use constructors that we are hiding on purpose in source? Is there an alternative way to create the credential, without using a hidden constructor?

**Comment by jasonjoh** [comment]
Thanks for flagging this @carlossanlop. With the latest version of Azure.Identity (1.8.2) this constructor is displayed in Intellisense, at least in VS Code Insiders.

![image](https://user-images.githubusercontent.com/8966342/226355781-d527c7dc-7170-40ba-a6a7-1fb4035e583c.png)

I just tested with Visual Studio, and it does not display! I wrote this tutorial with VS Code, so I never had an issue discovering that constructor. I agree that it's probably best to use the one constructor that they apparently want us to use :D.
