### ISSUE TITLE
ODataError

### ISSUE THREAD

**Issue by fynn3003** [microsoftgraph/microsoft-graph-training#148]
I followed your Tutorial (https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad).
When running the App, I can authenticate in the browser, and by clicking 1 and enter the access token gets displayed. Unfortunatly it is not possible to list the inbox and to send a mail. When trying to send a mail I get an error. The end of the Error says "msgraph.generated.models.o_data_errors.o_data_error.ODataError" I spent the last two days figuring out how to solve it but can't find a solution. All the Scopes are set correct, in the app and in the config.cfg file. I would be very thankful if someone could help me with that issue!

**Comment by fynn3003** [comment]
I have modified my code, now I use your code from the app-auth folder. I have added the list_inbox from the other tutorial. I still get the OData Error, so I wrapped the try/catch around my code like this:
    try:
            choice = int(input())
        except ValueError:
            choice = -1
    try:
        if choice == 0:
            print('Goodbye...')
        elif choice == 1:
            await display_access_token(graph)
        elif choice == 2:
            await list_users(graph)
        elif choice == 3:
            await make_graph_call(graph)
        elif choice == 4:
            await list_inbox(graph)
        else:
            print('Invalid choice!\n')
    except ODataError as e:
        print('Error:')
        if e.error is not None:
            print(e.error.code, e.error.message

when I now choose 4 it does not show an error, but just reopens the menu like this:
Please choose one of the following options:
0. Exit
1. Display access token
2. List users
3. Make a Graph call
4. List inbox

In the Azure app I have checked all the api permissions, both as app and delegated...

**Comment by jasonjoh** [comment]
You cannot use the `.me` with app only auth. Since no user is logged in, there is no "me" :D. If you're mixing app-only scenarios with delegated scenarios, you should have two graph clients: one for app-only and one for delegated, and use the appropriate client for each call.

**Comment by fynn3003** [comment]
thanks, isn't it possible at all to get the inbox items via app only auth? If it is possible, how do I need to change the code?

**Comment by jasonjoh** [comment]
Yes, it's possible. You'll need to first add the **Application** permission to your app registration for `Mail.Read`. This will allow your app to read mail from every user in your org.

Next, you'll need to get the `id` of the user for the mailbox you want to read. You've got code already to list users, so you should be able to get the ID from the one you want.

You'll need to replace this import statement:

```python
from msgraph.generated.me.mail_folders.item.messages.messages_request_builder import (
    MessagesRequestBuilder)
```

with this one:

```python
from msgraph.generated.users.item.mail_folders.item.messages.messages_request_builder import (
    MessagesRequestBuilder)
```

Then your code would look like this (replacing `THE_ID_OF_THE_USER` with the actual ID):

```python
messages = await self.app_client.users_by_id('THE_ID_OF_THE_USER').mail_folders_by_id(
    'inbox').messages.get(request_configuration=request_config)
```

**Comment by fynn3003** [comment]
Hey, unfortunately this is also not working.
I tried the following: I used your code for the user auth method. As I said before I always get an error when trying to read my inbox, so I wrapped the code as you described in your first answer. Then I get this message "ResourceNotFound Resource could not be discovered." when I browsed what it means I came along, that it could be I am lacking the permissions. But I validated, that all the permissions are selected correct and granted! I found another source where you said that it could be, that the company does not have an Exchange Online mailbox. Is this the only possible reason for it? Or can you suggest any different things to overcome this problem. I am struggling with it for days, but won't get further...

**Comment by fynn3003** [comment]
thanks, that information helps a lot, I will ask the administrator about it. One last question, I am trying to implement, that I can get Information about my OneNote notebooks, sections and pages. I tried to do it similar to the other snippets, but could not quite manage it, as I am also lacking of the necessary sdks and packages I need to install. Also I struggle to write the correct code. So I wanted to ask, if there is a good documentation for implementing one note with which I could work with, because I could not find anything good in the internet.

**Comment by jasonjoh** [comment]
OneNote APIs are on [Microsoft Graph](https://learn.microsoft.com/graph/api/resources/onenote-api-overview?view=graph-rest-1.0), but unfortunately I'm not familiar with them. The Python SDK is still in preview so it may not support these APIs fully.
