### ISSUE TITLE
Can successfully get token, but cannot get the User Info

### ISSUE THREAD

**Issue by ThomasUN000000000** [microsoftgraph/microsoft-graph-training#157]
![image](https://github.com/microsoftgraph/microsoft-graph-training/assets/137273222/7302e90d-bdbc-4d69-9d64-0a304c76bbab)
![image](https://github.com/microsoftgraph/microsoft-graph-training/assets/137273222/22c1fe44-cedb-4867-bcd4-f9ab83b87d4a)
I followed the training step by step, for the authentication step, it is working, however for the User info, I will not, the error info does not provide more info, so could anyone meet this error? thanks for your help!

**Comment by jasonjoh** [comment]
@ThomasUN000000000 I notice that you're logging into `https://microsoft.com/deviceloginchina`. Are you accessing Microsoft 365 in China? If so, I believe you need to make some code changes to connect to Microsoft Graph China.

[National cloud deployments](https://learn.microsoft.com/graph/deployments)

Try the solution suggested here: https://github.com/microsoftgraph/msgraph-sdk-python/issues/218#issuecomment-1562761675

**Comment by jasonjoh** [comment]
Closing due to no response.
