### ISSUE TITLE
AttributeError: 'GraphRequestAdapter' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by Jheesbrough** [microsoftgraph/microsoft-graph-training#164]
Python tutorial gives the error 

`AttributeError: 'GraphRequestAdapter' object has no attribute 'get_token'`.

Caused by the line `self.user_client = GraphServiceClient(self.adapter)`
which should be `self.user_client = GraphServiceClient(request_adapter=self.adapter)`

**Comment by jasonjoh** [comment]
Thanks for reporting this. It looks like the Python SDK updated their constructor for `GraphServiceClient` that broke this. Opened https://github.com/microsoftgraph/msgraph-training-python/issues/82 to fix.
