### ISSUE TITLE
Check status of mail sent using Microsoft graph. 

### ISSUE THREAD

**Issue by ANVLISTENER** [microsoftgraph/microsoft-graph-training#90]
Hello Team ,

How to know the Microsoft graph has sent a mail successfully for an email id. Make sure it hasn't failed.

This is for C#.

Kindly help.

Regards,
Libin

**Comment by jasonjoh** [comment]
Hi @ANVLISTENER, thanks for your interest in Microsoft Graph. This repository is for the source files for our getting started tutorials, and we're not setup to answer general questions here. Please post your question on [Microsoft Q&A](https://aka.ms/askgraph).
